### ISSUE TITLE
[PORTUGAL] Avaloq Developer - Remote

### ISSUE THREAD

**Issue by JoseCastellaniNeto** [CASTECH-Software-Solutions/open_roles#11]
> English: B2 Upper Intermediate
Remote from Portugal 

## About the company ##

LUXOFT

A design, data, and IT service development company represented in 21 countries with 17 000+ employees globally and headquarters in Switzerland.

The company provides end-to-end technology solutions for mission-critical systems, products, and services, and helps create data-fueled organizations, solving complex operational, technological, and strategic challenges. Its main aim and passion are building resilient businesses while generating new business channels and revenue streams, exceptional user experiences, and modernized operations at scale.

## About the project ##

The Wealth Management Practice and Avaloq operations in Europe is currently being expanded due to client demand across a number of high profile projects.
Great opportunities to work within a dynamic, international team led by industry experts within market leading technologies, with prestigious tier one clients in a demanding and progressive atmosphere. As a part of the team, you will take part in Avaloq Banking Suite implementation initiatives throughout their entire life cycle.

## Responsibilities ##

Participation in implementation of Avaloq Core Banking Platform
Analyzing requirements and designing software solutions
Writing business and technical specifications
Performing parameterization and customization of various core banking software modules
Designing and developing user interfaces
Designing and executing manual and automated test cases
Providing technical expertise and support for internal and external stakeholders

## Requirements ##

Avaloq Certification (valid or expired)
At least 3-5 years of Avaloq parametrisation experience
Participation in multiple Avaloq Core Banking Platform implementations in the business
Ability to develop high level software designs and solutions
Excellent analytical skills and systematic approach to problem solving
Ability to articulate complex technical issues to business stakeholders
High customer orientation
Excellent interpersonal and communication skills with a good command of written and spoken English.
Willingness to travel abroad

## Nice to have ##

Experience as a Business Analyst in multiple banking domains is a strong advantage
Avaloq GIMF Certification

## Benefits ##

What can you expect?
Dynamic collaborative international team of professionals in a fast-growing global company
Opportunity to learn and use new technologies
Ongoing learning and growth opportunities
Varied challenging hands-on projects
Competitive remuneration and bonus system
Work mode flexibility
Partial coverage of transport costs from and to work
Life Insurance
Parental leave

**Comment by nhano006** [comment]
Hello Jose,

where should we send application?

cheers
