### ISSUE TITLE
[PORTUGAL - Lisbon] Team Lead with Java

### ISSUE THREAD

**Issue by JoseCastellaniNeto** [CASTECH-Software-Solutions/open_roles#14]
> English: B2 Upper Intermediate
Location: Lisbon, Portugal - maximum flexible and comfortable mode: office / home office

## About the company ##

LUXOFT

A design, data, and IT service development company represented in 21 countries with 17 000+ employees globally and headquarters in Switzerland.

The company provides end-to-end technology solutions for mission-critical systems, products, and services, and helps create data-fueled organizations, solving complex operational, technological, and strategic challenges. Its main aim and passion are building resilient businesses while generating new business channels and revenue streams, exceptional user experiences, and modernized operations at scale.

## Technology stack includes ##
Java 8 / Java 11, Spring, SpringBoot, Oracle Coherence, DataSynapse, Kafka, Solace JMS, Apache Tomcat, Web services, Sybase, Oracle DB, MS SQL, PostgreSQL, HTML5, Node.js, Git, Python, JIRA, Confluence, BitBucket, Jenkins / TeamCity / Ansible, RunDesk, Docker / Kubernetes, SDLC, Sonar, Geneos / Grafana / Prometheus

## Responsibilities ##

Design and develop new functionality
Working with Scrum Masters, BAs & other team mates on functional and non-functional requirements, technical analysis and design
Coding and testing, reviewing other team member's changes
Document business and functional requirements, design decisions and API
Co-working with QA team on test automation of new and existing functionality
Contribute to the definition of the future state of the system architecture
When product and architecture experience gained, mentor and direct more junior developers
Requirements
Java, Apache Maven, Orace Database, TeamCity, Jenkins, Git, Apache Tomcat, Agile Methodology, Hiberante, JIRA, JMS Servers, SQL, UNIX, Sybase

## Nice to have ##

EA, TDD methodology, Hazelcast, Sonar, Docker, SPARK, Apache Kafka, Hadoop, Coherence

## Benefits ##
What can you expect?

Dynamic collaborative international team of professionals in a fast-growing global company
Opportunity to learn and use new technologies
Ongoing learning and growth opportunities
Varied challenging hands-on projects
Competitive remuneration and bonus system
Work mode flexibility
Partial coverage of transport costs from and to work
Health insurance
Parental leave

**Comment by adilwahla** [comment]
@JoseCastellaniNeto Sir can i apply for remote position?
I am a Software Engineer 
Thanks for such opportunity
