### ISSUE TITLE
[PORTUGAL] Senior Flutter Developer - Remote

### ISSUE THREAD

**Issue by JoseCastellaniNeto** [CASTECH-Software-Solutions/open_roles#16]
> English: B2 Upper Intermediate
Location: Lisbon, Portugal - Remote - home office

## About the company ##

LUXOFT

A design, data, and IT service development company represented in 21 countries with 17 000+ employees globally and headquarters in Switzerland.

The company provides end-to-end technology solutions for mission-critical systems, products, and services, and helps create data-fueled organizations, solving complex operational, technological, and strategic challenges. Its main aim and passion are building resilient businesses while generating new business channels and revenue streams, exceptional user experiences, and modernized operations at scale.

## About the project ##

The Client is the world's largest manufacturer of professional dental products and technologies, with a more than a 100-year history of innovation and service to the dental industry and patients worldwide. The Client develops, manufactures, and markets a comprehensive solution offering including dental and oral health products as well as other consumable medical devices under a strong portfolio of world-class brands. Our Client's products provide innovative, high-quality, and effective solutions to advance patient care and deliver better and safer dentistry.
The project is a recently started development of a web Flutter application for dentists and patients.

## Responsibilities ##

- Development of new components of the system
- Active participation in the architecture of the backend
- Participation in the code review process
- Collaborative work in an Agile environment together with the engineering team and product owners
- To be the only front-end developer in a team (to be proactive and pull things forward)
- To have experience with web-applications

## Requirements ##
To be the only front-end developer in a team (to be proactive and pull things forward)
To have experience with development of web applications
Flutter (3+ of commercial experience with Flutter)
Dart

## Nice to have ##

Golang (basic)
Scrum framework

## Benefits ##
What can you expect?

Dynamic collaborative international team of professionals in a fast-growing global company
Opportunity to learn and use new technologies
Ongoing learning and growth opportunities
Varied challenging hands-on projects
Competitive remuneration and bonus system
Work mode flexibility
Partial coverage of transport costs from and to work
Life Insurance
Parental leave

**Comment by adilwahla** [comment]
@JoseCastellaniNeto Hello sir I am interested in Flutter Development Remote position 
where should i share my resume?

**Comment by EduProgOliveira** [comment]
Boa tarde, tenho interesse na vaga, onde me inscrevo ?
