### ISSUE TITLE
[PORTUGAL - Lisbon] Senior Java Developer 

### ISSUE THREAD

**Issue by JoseCastellaniNeto** [CASTECH-Software-Solutions/open_roles#23]
> English: B2 Upper Intermediate 
Location: Lisbon - Remote - home office

## About the company ##

LUXOFT

A design, data, and IT service development company represented in 21 countries with 17 000+ employees globally and headquarters in Switzerland.

The company provides end-to-end technology solutions for mission-critical systems, products, and services, and helps create data-fueled organizations, solving complex operational, technological, and strategic challenges. Its main aim and passion are building resilient businesses while generating new business channels and revenue streams, exceptional user experiences, and modernized operations at scale.

## About the project ##

With award-winning mobile banking apps and trading systems, our technology platforms help Bank deliver best-in-class products to clients. Naturally, we make sure that the phones work, emails are delivered and PCs run - but we also develop innovative collaboration platforms and workspaces that help our people share their knowledge, their expertise and their passion for our business.

Developments in technology are changing the way we communicate, work and even think. Join us here, and you'll constantly be looking ahead. At this role you are expected to capitalize on new technological trends that can reshape the business and deliver value for the clients, whilst still meeting the demands of customers, regulators and the markets.

Technology stack includes: Java 8 / Java 11, Spring, SpringBoot, Oracle Coherence, DataSynapse, Kafka, Solace JMS, Apache Tomcat, Web services, Sybase, Oracle DB, MS SQL, PostgreSQL, HTML5, Node.js, Git, Python, JIRA, Confluence, BitBucket, Jenkins / TeamCity / Ansible, RunDesk, Docker / Kubernetes, SDLC, Sonar, Geneos / Grafana / Prometheus

We offer our engineers to work in maximum flexible and comfortable mode: office / home

## Responsibilities ##

Design and develop new functionality
Working with Scrum Masters, BAs & other team mates on functional and non-functional requirements, technical analysis and design
Coding and testing, reviewing other team member's changes
Document business and functional requirements, design decisions and API
Co-working with QA team on test automation of new and existing functionality
Contribute to the definition of the future state of the system architecture
When product and architecture experience gained, mentor and direct more junior developers

## Requirements ##

Java, Apache Maven, Orace Database, TeamCity, Jenkins, Git, Apache Tomcat, Agile Methodology, Hiberante, JIRA, JMS Servers, SQL, UNIX, Sybase

## Nice to have ##

EA, TDD methodology, Hazelcast, Sonar, Docker, SPARK, Apache Kafka, Hadoop, Coherence

## Benefits ##
What can you expect?

Dynamic collaborative international team of professionals in a fast-growing global company
Opportunity to learn and use new technologies
Ongoing learning and growth opportunities
Varied challenging hands-on projects
Competitive remuneration and bonus system
Work mode flexibility
Partial coverage of transport costs from and to work
Life Insurance
Parental leave

**Comment by andrejacinto50** [comment]
Aqui e o André Filipe Jacinto, estou cursando o curso de Analise e Desenvolvimento de Sistemas.
De maio de 2021 a dezembro de 2023 estagiei no Sesc Santa Catarina, lá tive experiência com sistemas de 
alta perfomance e com isso hoje me sinto preparado para pegar uma vaga efetiva que encaixa no meu perfil.
Estou te enviando meu curriculo para caso você saber que tenha alguma vaga disponível me avisar.
[curriculo5.pdf](https://github.com/CASTECH-Software-Solutions/open_roles/files/10805902/curriculo5.pdf)
